# Autogenerated wrapper script for Qt6QuickTimeline_jll for aarch64-apple-darwin
export libqt6charts, libqt6chartsqml

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6QuickTimeline")
JLLWrappers.@declare_library_product(libqt6charts, "@rpath/QtQuickTimeline")
JLLWrappers.@declare_library_product(libqt6chartsqml, "@rpath/QtQuickTimelineBlendTrees")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6charts,
        "lib/QtQuickTimeline.framework/Versions/A/QtQuickTimeline",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6chartsqml,
        "lib/QtQuickTimelineBlendTrees.framework/Versions/A/QtQuickTimelineBlendTrees",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
