# Autogenerated wrapper script for Qt6QuickTimeline_jll for aarch64-linux-musl-cxx11
export libqt6timeline, libqt6timelineblendtrees

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6QuickTimeline")
JLLWrappers.@declare_library_product(libqt6timeline, "libQt6QuickTimeline.so.6")
JLLWrappers.@declare_library_product(libqt6timelineblendtrees, "libQt6QuickTimelineBlendTrees.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6timeline,
        "lib/libQt6QuickTimeline.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6timelineblendtrees,
        "lib/libQt6QuickTimelineBlendTrees.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
