# Autogenerated wrapper script for Qt6QuickTimeline_jll for aarch64-linux-gnu-cxx11
export libqt6charts, libqt6chartsqml

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6QuickTimeline")
JLLWrappers.@declare_library_product(libqt6charts, "libQt6QuickTimeline.so.6")
JLLWrappers.@declare_library_product(libqt6chartsqml, "libQt6QuickTimelineBlendTrees.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6charts,
        "lib/libQt6QuickTimeline.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6chartsqml,
        "lib/libQt6QuickTimelineBlendTrees.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
