# Autogenerated wrapper script for Qt6QuickTimeline_jll for x86_64-w64-mingw32-cxx03
export libqt6charts, libqt6chartsqml

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6QuickTimeline")
JLLWrappers.@declare_library_product(libqt6charts, "Qt6QuickTimeline.dll")
JLLWrappers.@declare_library_product(libqt6chartsqml, "Qt6QuickTimelineBlendTrees.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6charts,
        "bin\\Qt6QuickTimeline.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6chartsqml,
        "bin\\Qt6QuickTimelineBlendTrees.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
